# Generated by Django 3.1.3 on 2021-10-06 04:30

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=10)),
                ('year', models.IntegerField(default=2021)),
                ('income', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
                ('expenses', models.IntegerField(default=0)),
                ('transactions', models.IntegerField(default=0)),
                ('savings', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BudgetUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=database.models.Get_UUID, max_length=50, primary_key=True, serialize=False)),
                ('date', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=15)),
                ('amount', models.IntegerField(default=10)),
                ('category', models.CharField(default='miscellaneous', max_length=30)),
                ('month_budget_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_budget_connected_to_transaction', to='database.monthlybudget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.CharField(default=database.models.Get_UUID, max_length=50, primary_key=True, serialize=False)),
                ('date', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=15)),
                ('amount', models.IntegerField(default=10)),
                ('category', models.CharField(default='miscellaneous', max_length=30)),
                ('month_budget_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_budget_connected_to_expense', to='database.monthlybudget')),
            ],
        ),
    ]
