# Generated by Django 3.1.3 on 2021-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='savings_index',
            field=models.IntegerField(default=0),
        ),
    ]
